print("Adonai, my shepherd:")
print("I know no need.")
print("In lush meadows")
print("you invite my soul to rest and recline; together")
print()

print("we walk beside the dance of light on quiet waters.")
print("You give me back myself,")
print("point me to the road toward justice,")
print("one of your sacred names.")
print()

print("Even when I walk in a valley")
print("dark as the shadow of death,")
print("I know no fear, for you are near me")
print("with your staff and crook, and I am safe.")
print()

print("You spread out a feast before me")
print("twith those who were my enemies.")
print("You touch my head with fragrant oil;")
print("my thanks overflows.")
print()

print("May goodness and mercy")
print("follow me all the days of my life,")
print("and may I make my home")
print("in the house of the Lord forever.")
print()
print("  Tim Lucas")
